server:
  port: 9000

spring:
  application:
    name: springcloud-config-dev
  datasource:
    #mysqL驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://ericjaylsh.dev.xyz:3306/ericjaylsh_springcloud?useUnicode=true&characterEncoding=utf-8&usesSL=false
    password: 123456
    username: root
    druid:
      test-while-idle: false

eureka:
  client:
    service-url:
      defaultZone: http://ericjaylsh.dev.xyz:7001/eureka/
     # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    
    
#自定义的配置信息用于测试客户端读取
ericjaylsh: 
  info: 这里是配置中心的 config-dev.yml文件 你成功地找到了我 爱你呦 我一路向北 离开有你的季节 你说你好累 已无法再爱上谁 风在上路吹 过往的画面全都是我不对 细数惭愧 我想你几回
  mojito: you are my honey

    
     

